services:
  - docker:dind

stages:
  - build
  - test

build:
  stage: build
  image: docker:latest
  script:
    - echo "Building project..."
    - docker build -t docker-react-project -f Dockerfile.dev .
    - echo "Finished building"

basic-test:
  stage: test
  image: docker:latest
  script:
    - echo "Running tests..."
    - docker run -e CI=true docker-react-project npm run test